[phases.setup]
nixpkgs = ["nodejs_20", "chromium", "cairo", "pango", "giflib", "libjpeg", "librsvg", "pixman"]

[phases.install]
cmds = ["npm install --production"]

[start]
cmd = "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true PUPPETEER_EXECUTABLE_PATH=$(which chromium) node server.js"
